name: CI

on:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run ShellCheck
        run: make lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, debian]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and Test
        run: make build-${{ matrix.os }} test-${{ matrix.os }}
